site_name: gptref
theme:
  name: material
  font:
    text: PT Sans
  features:
    - navigation.tabs
  palette: 
    # Palette toggle for light mode
    - primary: black
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      execute: true
      execute_ignore: "docs/data/*.py"
  - exclude:
      glob:
        - questions.md
  
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true