title: Statsbook
author: Chansoo Song
only_build_toc_files: true
collapse_inactive_chapters: true
repository:
  url: github.com/chansooligans/statsbook
html:
  use_repository_button: true
  use_issues_button: true
execute:
  execute_notebooks: cache
  allow_errors: true
  timeout: 60
parse:
  myst_enable_extensions:
      - tasklist
      - dollarmath
sphinx:
  config:
    nb_custom_formats:
        .py:
            - jupytext.reads
            - fmt: py:percent